version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  setup_and_lint: 
    docker:
      - image: cimg/python:3.8
      
    working_directory: ~/repo
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-dependencies--{{ checksum "requirements.txt" }}
            - v1-dependencies
            
      - run:
          name: install_dependencies
          command: |
            python3 -m venv docker_venv
            . docker_venv/bin/activate
            pip install -r requirements.txt
            
      - save_cache:
          paths:
            - docker_venv
          key1: v1-dependencies--{{ checksum "requirements.txt" }}
            
      - python/install-packages:
          pkg-manager: pip
          
      - run:
          name: Run lint
          command: |
            . docker_venv/bin/activate
            make lint

workflows:
  docker_deploy_sample:
    jobs:
      - setup_and_lint